base: 'https://webconsulting-typo3-lab.ddev.site/astryx-typo3/'
baseVariants:
  -
    base: 'https://typo3-lab.webconsulting.at/astryx-typo3/'
    condition: 'applicationContext == "Production"'
rootPageId: 1290
websiteTitle: 'Astryx'
dependencies:
  - webconsulting/astryx-typo3
  - webconsulting/astryx-typo3-content-elements
  - webconsulting/astryx-typo3-search
solr_enabled_read: true
solr_host_read: typo3-solr
solr_path_read: /
solr_port_read: '8983'
solr_scheme_read: http
solr_use_write_connection: false
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=1295'
languages:
  -
    languageId: 0
    title: English
    navigationTitle: English
    locale: en_US.UTF-8
    base: /
    flag: us
    iso-639-1: en
    fallbackType: strict
    solr_core_read: core_en
  -
    languageId: 1
    title: German
    navigationTitle: Deutsch
    locale: de_AT.UTF-8
    base: /de/
    flag: de
    iso-639-1: de
    fallbackType: fallback
    fallbacks: '0'
    solr_core_read: core_de
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    map:
      sitemap.xml: 1533906435
      robots.txt: 201
