base: 'https://webconsulting-typo3-lab.ddev.site/desiderio/'
dependencies:
  - webconsulting/solr-defaults
  - studiomitte/friendlycaptcha
  - webconsulting/desiderio-powermail
  - webconsulting/desiderio-content-elements
  - webconsulting/desiderio-blog-standalone
  - webconsulting/desiderio-preset-corporate
  - dirnbauer/innesto
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=737'
friendlycaptcha_js_path: 'EXT:friendlycaptcha_official/Resources/Public/JavaScript/lib/sdk@0.1.26-site.compat.min.js'
friendlycaptcha_secret_key: ddev-secret-key
friendlycaptcha_site_key: ddev-site-key
friendlycaptcha_skip_dev_validation: true
friendlycaptcha_use_eu_puzzle_endpoint: false
friendlycaptcha_verify_url: 'https://global.frcapi.com/api/v2/captcha/siteverify'
languages:
  -
    languageId: 0
    title: English
    navigationTitle: English
    locale: en_US.UTF-8
    base: /
    flag: us
    iso-639-1: en
    fallbackType: strict
    solr_core_read: core_en
  -
    languageId: 1
    title: German
    navigationTitle: Deutsch
    locale: de_AT.UTF-8
    base: /de/
    flag: de
    iso-639-1: de
    fallbackType: fallback
    solr_core_read: core_de
  -
    languageId: 2
    title: 'Chinese (Simplified)'
    navigationTitle: 中文
    locale: zh_CN.UTF-8
    base: /zh/
    flag: cn
    iso-639-1: zh
    fallbackType: fallback
    solr_core_read: core_zh
  -
    languageId: 3
    title: Hungarian
    navigationTitle: Magyar
    locale: hu_HU.UTF-8
    base: /hu/
    flag: hu
    iso-639-1: hu
    fallbackType: fallback
    solr_core_read: core_hu
rootPageId: 505
routeEnhancers:
  SolrSearch:
    type: SolrFacetMaskAndCombineEnhancer
    extensionKey: tx_solr
    limitToPages:
      - 738
    solr:
      query:
        concat: true
        mask: true
        map:
          type: type
    routePath: '/{type}'
    _arguments:
      type: filter-type
    requirements:
      type: '.*'
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    map:
      sitemap.xml: 1533906435
      robots.txt: 201
      suggest.json: 7384
solr_enabled_read: true
solr_host_read: typo3-solr
solr_path_read: /
solr_port_read: '8983'
solr_scheme_read: http
solr_use_write_connection: false
websiteTitle: 'Desiderio'
imports:
  -
    resource: 'EXT:blog/Configuration/Routes/Default.yaml'
  -
    resource: '../../shared/route-enhancers.yaml'
