desiderio.footer.legalPageIds: '734,735,736'
desiderio.search.targetPageId: '738'
desiderio.seo.defaultDescription: 'TYPO3Camp Vienna 2026 lab site for Desiderio TYPO3 page templates and content elements.'
desiderio.consent.privacyPageId: '735'
desiderio.tracking.enabled: false
desiderio.seo.robotsTxtEnabled: true
desiderio.seo.sitemapPath: sitemap.xml
