RUN set -eux; \
    apt-get update; \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends locales; \
    sed -i 's/^# *\(hu_HU.UTF-8 UTF-8\)/\1/' /etc/locale.gen; \
    sed -i 's/^# *\(zh_CN.UTF-8 UTF-8\)/\1/' /etc/locale.gen; \
    locale-gen hu_HU.UTF-8 zh_CN.UTF-8; \
    rm -rf /var/lib/apt/lists/*
