base: 'https://webconsulting-typo3-lab.ddev.site/mtug-camp-munich-2026/'
dependencies:
  - webconsulting/site-package-search
  - studiomitte/friendlycaptcha
  - webconsulting/desiderio-powermail
  - webconsulting/desiderio-content-elements
  - webconsulting/desiderio-preset-corporate
  - desiderio/content-blocks-bundle
friendlycaptcha_js_path: 'EXT:friendlycaptcha_official/Resources/Public/JavaScript/lib/sdk@0.1.26-site.compat.min.js'
friendlycaptcha_secret_key: ddev-secret-key
friendlycaptcha_site_key: ddev-site-key
friendlycaptcha_skip_dev_validation: true
friendlycaptcha_use_eu_puzzle_endpoint: false
friendlycaptcha_verify_url: 'https://global.frcapi.com/api/v2/captcha/siteverify'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=938'
languages:
  -
    languageId: 0
    title: German
    navigationTitle: Deutsch
    locale: de_DE.UTF-8
    base: /
    flag: de
    iso-639-1: de
    fallbackType: strict
  -
    languageId: 1
    title: English
    navigationTitle: English
    locale: en_US.UTF-8
    base: /en/
    flag: us
    iso-639-1: en
    fallbackType: fallback
  -
    languageId: 2
    title: 'Chinese (Simplified)'
    navigationTitle: 中文
    locale: zh_CN.UTF-8
    base: /zh/
    flag: cn
    iso-639-1: zh
    fallbackType: fallback
  -
    languageId: 3
    title: Hungarian
    navigationTitle: Magyar
    locale: hu_HU.UTF-8
    base: /hu/
    flag: hu
    iso-639-1: hu
    fallbackType: fallback
rootPageId: 933
websiteTitle: 'TYPO3 Camp München 2026'
imports:
  -
    resource: '../../shared/route-enhancers.yaml'
  -
    resource: 'EXT:blog/Configuration/Routes/Default.yaml'
