config: "vendor/apache-solr-for-typo3/solr/Resources/Private/Solr/solr.xml"
typo3lib: "vendor/apache-solr-for-typo3/solr/Resources/Private/Solr/typo3lib"
configsets:
  - name: "ext_solr_14_0_0"
    path: "vendor/apache-solr-for-typo3/solr/Resources/Private/Solr/configsets/ext_solr_14_0_0"
    cores:
      - name: "core_ar"
        schema: "arabic/schema.xml"
      - name: "core_hy"
        schema: "armenian/schema.xml"
      - name: "core_eu"
        schema: "basque/schema.xml"
      - name: "core_ptbr"
        schema: "brazilian_portuguese/schema.xml"
      - name: "core_bg"
        schema: "bulgarian/schema.xml"
      - name: "core_my"
        schema: "burmese/schema.xml"
      - name: "core_ca"
        schema: "catalan/schema.xml"
      - name: "core_zh"
        schema: "chinese/schema.xml"
      - name: "core_cs"
        schema: "czech/schema.xml"
      - name: "core_da"
        schema: "danish/schema.xml"
      - name: "core_nl"
        schema: "dutch/schema.xml"
      - name: "core_en"
        schema: "english/schema.xml"
      - name: "core_fi"
        schema: "finnish/schema.xml"
      - name: "core_fr"
        schema: "french/schema.xml"
      - name: "core_gl"
        schema: "galician/schema.xml"
      - name: "core_generic"
        schema: "generic/schema.xml"
      - name: "core_de"
        schema: "german/schema.xml"
      - name: "core_el"
        schema: "greek/schema.xml"
      - name: "core_hi"
        schema: "hindi/schema.xml"
      - name: "core_hu"
        schema: "hungarian/schema.xml"
      - name: "core_id"
        schema: "indonesian/schema.xml"
      - name: "core_ie"
        schema: "irish/schema.xml"
      - name: "core_it"
        schema: "italian/schema.xml"
      - name: "core_ja"
        schema: "japanese/schema.xml"
      - name: "core_km"
        schema: "khmer/schema.xml"
      - name: "core_ko"
        schema: "korean/schema.xml"
      - name: "core_lo"
        schema: "lao/schema.xml"
      - name: "core_lv"
        schema: "latvia/schema.xml"
      - name: "core_no"
        schema: "norwegian/schema.xml"
      - name: "core_fa"
        schema: "persian/schema.xml"
      - name: "core_pl"
        schema: "polish/schema.xml"
      - name: "core_pt"
        schema: "portuguese/schema.xml"
      - name: "core_ro"
        schema: "romanian/schema.xml"
      - name: "core_ru"
        schema: "russian/schema.xml"
      - name: "core_rs"
        schema: "serbian/schema.xml"
      - name: "core_es"
        schema: "spanish/schema.xml"
      - name: "core_sv"
        schema: "swedish/schema.xml"
      - name: "core_th"
        schema: "thai/schema.xml"
      - name: "core_tr"
        schema: "turkish/schema.xml"
      - name: "core_uk"
        schema: "ukrainian/schema.xml"
