base: 'https://webconsulting-typo3-lab.ddev.site/aktuelle-temperaturen/'
dependencies:
  - webconsulting/site-package-desiderio-corporate
languages:
  -
    languageId: 0
    title: Deutsch
    navigationTitle: Deutsch
    locale: de_DE.UTF-8
    base: /
    flag: de
    iso-639-1: de
    fallbackType: strict
  -
    languageId: 1
    title: English
    navigationTitle: English
    locale: en_US.UTF-8
    base: /en/
    flag: us
    iso-639-1: en
    fallbackType: strict
rootPageId: 1111
