services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Webconsulting\SitePackage\:
    resource: '../Classes/*'

  Hn\Agent\Service\ToolConverterService:
    alias: Webconsulting\SitePackage\Service\AgentToolConverterService
