ServerName typo3-lab.webconsulting.at

<VirtualHost *:80>
    ServerName typo3-lab.webconsulting.at
    DocumentRoot /var/www/html/public

    SetEnvIf X-Forwarded-Proto "https" HTTPS=on
    RemoteIPHeader X-Forwarded-For
    RemoteIPInternalProxy 10.0.0.0/8
    RemoteIPInternalProxy 172.16.0.0/12
    RemoteIPInternalProxy 192.168.0.0/16

    <Directory /var/www/html/public>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <Location />
        AuthType Basic
        AuthName "TYPO3 Lab"
        AuthBasicProvider file
        AuthUserFile /etc/apache2/typo3-lab.htpasswd
        Require valid-user
    </Location>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
