name: webconsulting/site-package-desiderio-corporate
label: 'Site Package: Desiderio Corporate'
dependencies:
  - webconsulting/site-package-search
  - webconsulting/desiderio-preset-corporate
  - webconsulting/desiderio-shadcnui-templates
