name: webconsulting-typo3-lab
type: typo3
docroot: public
php_version: "8.3"
webserver_type: apache-fpm
xdebug_enabled: false
performance_mode: mutagen
database:
  type: mariadb
  version: "10.11"
upload_dirs:
  - fileadmin
  - ../packages/flue-bridge/node_modules
  - ../vendor/webconsulting/docx-editor/node_modules
use_dns_when_possible: true
share_default_provider: cloudflared
composer_version: "2"
ddev_version_constraint: ">= v1.25.2"
web_environment:
  - TYPO3_CONTEXT=Development
corepack_enable: false

hooks:
  post-start:
    - exec-host: ddev solrctl apply --no-start
