dependencies:
  - dirnbauer/site-package
languages:
  -
    title: Chinese
    languageId: 1
    base: /zh/
    locale: zh_CN.UTF-8
    navigationTitle: Chinese
    flag: cn
    iso-639-1: zh
    fallbackType: fallback
